### ISSUE TITLE
name labels in different languages

### ISSUE THREAD

**Issue by joelthill** [weso/SAF-Lux#25] opened 2021-07-13 16:05 UTC
attributing language qualifiers to names (in the labels section at the very top of each item) may be problematic. where do these come from and how to handle them? for most of the persons, this is just not correct.

**Comment by digitaalwerktuig** [comment] 2021-07-15 09:17
The current setup assumes the preffered name should be used for the labels section at the very top of the item. See heading:name in the Excel sheet.

**Comment by mzeinstra** [comment] 2021-07-15 09:31
Is this a duplicate of #28 ?

**Comment by mzeinstra** [comment] 2021-08-06 07:35
Moved this to https://github.com/natliblux/saf-wikibase/issues/20

**Closed by mzeinstra** 2021-08-06 07:35 UTC
